---
  header_logo_url: http://Chrysididae.archive.speciesfile.org/HomePage/Chrysididae/img_Logo/SiteLogo.jpg
  header_logo_text: Chysididae Species File
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
