---
  header_logo_url: Chysididae.archive.speciesfile.org/HomePage/Chrysididae/img_logo/SiteLogo.jpg
  header_logo_text: Chysididae Species File
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
