---
  project_name: "Chysididae Species File"
  project_citation: "Chysididae Species File"
  project_authors: "Baker E, Kimsey L, Bohart, R"
  project_url: "https://Chysididae.speciesfile.org'."
  project_old_url: "http://Chysididae.archive.speciesfile.org'." 
  focal_taxon: "chysididae"
  focal_taxon_common_name: "parasitic wasps of stick insects"
  contact_email: "edwbaker@gmail.com"
